kind: DataContract
apiVersion: v3.0.0
id: week2-contract-v1
info:
  title: Week2 Contract
  version: 1.0.0
servers:
  local:
    type: local
    path: outputs/week2/verdicts.jsonl
    format: jsonl
schema:
  type: object
  properties:
    verdict_id:
      type: string
      description: Field 'verdict_id' of type string.
      required: true
      unique: true
    target_ref:
      type: string
      description: Field 'target_ref' of type string.
      required: true
      unique: false
    rubric_id:
      type: string
      description: Field 'rubric_id' of type string.
      required: true
      unique: false
    rubric_version:
      type: string
      description: Field 'rubric_version' of type string.
      required: true
      unique: false
    evaluated_at:
      type: string
      description: Field 'evaluated_at' of type string.
      required: true
      unique: true
    confidence:
      type: number
      description: Field 'confidence' of type number.
      required: true
      unique: false
      minimum: 0.0
      maximum: 1.0
    overall_score:
      type: number
      description: Field 'overall_score' of type number.
      required: true
      unique: false
      minimum: 3.013
      maximum: 4.878
    overall_verdict:
      type: string
      description: Field 'overall_verdict' of type string.
      required: true
      unique: false
    scores:
      type: object
      properties:
        Correctness:
          type: object
          properties:
            score:
              type: number
              description: 'Field ''scores.Correctness.score'' of type number. Warning:
                54.0% missing.'
              required: false
              unique: false
              minimum: 3.0
              maximum: 5.0
            evidence:
              type: array
              items:
                type: string
                description: 'Field ''scores.Correctness.evidence'' of type string.
                  Warning: 54.0% missing.'
                required: false
                unique: false
              description: 'Field ''scores.Correctness.evidence'' of type array. Warning:
                54.0% missing.'
              required: false
              unique: false
            notes:
              type: string
              description: 'Field ''scores.Correctness.notes'' of type string. Warning:
                54.0% missing.'
              required: false
              unique: false
        Security:
          type: object
          properties:
            score:
              type: number
              description: 'Field ''scores.Security.score'' of type number. Warning:
                52.9% missing.'
              required: false
              unique: false
              minimum: 3.0
              maximum: 5.0
            evidence:
              type: array
              items:
                type: string
                description: 'Field ''scores.Security.evidence'' of type string. Warning:
                  52.9% missing.'
                required: false
                unique: false
              description: 'Field ''scores.Security.evidence'' of type array. Warning:
                52.9% missing.'
              required: false
              unique: false
            notes:
              type: string
              description: 'Field ''scores.Security.notes'' of type string. Warning:
                52.9% missing.'
              required: false
              unique: false
quality:
  type: SodaChecks
  checks:
  - type: missing_count
    column: verdict_id
    must_be: '='
    value: 0
    name: verdict_id_no_missing_values
  - type: duplicate_count
    column: verdict_id
    must_be: '='
    value: 0
    name: verdict_id_no_duplicates
  - type: missing_count
    column: target_ref
    must_be: '='
    value: 0
    name: target_ref_no_missing_values
  - type: missing_count
    column: rubric_id
    must_be: '='
    value: 0
    name: rubric_id_no_missing_values
  - type: missing_count
    column: rubric_version
    must_be: '='
    value: 0
    name: rubric_version_no_missing_values
  - type: missing_count
    column: evaluated_at
    must_be: '='
    value: 0
    name: evaluated_at_no_missing_values
  - type: duplicate_count
    column: evaluated_at
    must_be: '='
    value: 0
    name: evaluated_at_no_duplicates
  - type: missing_count
    column: confidence
    must_be: '='
    value: 0
    name: confidence_no_missing_values
  - type: min
    column: confidence
    must_be: '>='
    value: 0.0
    name: confidence_min_value
  - type: max
    column: confidence
    must_be: <=
    value: 1.0
    name: confidence_max_value
  - type: missing_count
    column: overall_score
    must_be: '='
    value: 0
    name: overall_score_no_missing_values
  - type: min
    column: overall_score
    must_be: '>='
    value: 3.013
    name: overall_score_min_value
  - type: max
    column: overall_score
    must_be: <=
    value: 4.878
    name: overall_score_max_value
  - type: missing_count
    column: overall_verdict
    must_be: '='
    value: 0
    name: overall_verdict_no_missing_values
  - type: missing_count
    column: scores.Correctness.score
    must_be: '='
    value: 0
    name: scores.Correctness.score_no_missing_values
  - type: min
    column: scores.Correctness.score
    must_be: '>='
    value: 3.0
    name: scores.Correctness.score_min_value
  - type: max
    column: scores.Correctness.score
    must_be: <=
    value: 5.0
    name: scores.Correctness.score_max_value
  - type: missing_count
    column: scores.Correctness.evidence
    must_be: '='
    value: 0
    name: scores.Correctness.evidence_no_missing_values
  - type: missing_count
    column: scores.Correctness.notes
    must_be: '='
    value: 0
    name: scores.Correctness.notes_no_missing_values
  - type: missing_count
    column: scores.Security.score
    must_be: '='
    value: 0
    name: scores.Security.score_no_missing_values
  - type: min
    column: scores.Security.score
    must_be: '>='
    value: 3.0
    name: scores.Security.score_min_value
  - type: max
    column: scores.Security.score
    must_be: <=
    value: 5.0
    name: scores.Security.score_max_value
  - type: missing_count
    column: scores.Security.evidence
    must_be: '='
    value: 0
    name: scores.Security.evidence_no_missing_values
  - type: missing_count
    column: scores.Security.notes
    must_be: '='
    value: 0
    name: scores.Security.notes_no_missing_values
  - type: missing_count
    column: scores.Readability.score
    must_be: '='
    value: 0
    name: scores.Readability.score_no_missing_values
  - type: min
    column: scores.Readability.score
    must_be: '>='
    value: 3.0
    name: scores.Readability.score_min_value
  - type: max
    column: scores.Readability.score
    must_be: <=
    value: 5.0
    name: scores.Readability.score_max_value
  - type: missing_count
    column: scores.Readability.evidence
    must_be: '='
    value: 0
    name: scores.Readability.evidence_no_missing_values
  - type: missing_count
    column: scores.Readability.notes
    must_be: '='
    value: 0
    name: scores.Readability.notes_no_missing_values
  - type: missing_count
    column: scores.Testability.score
    must_be: '='
    value: 0
    name: scores.Testability.score_no_missing_values
  - type: min
    column: scores.Testability.score
    must_be: '>='
    value: 3.0
    name: scores.Testability.score_min_value
  - type: max
    column: scores.Testability.score
    must_be: <=
    value: 5.0
    name: scores.Testability.score_max_value
  - type: missing_count
    column: scores.Testability.evidence
    must_be: '='
    value: 0
    name: scores.Testability.evidence_no_missing_values
  - type: missing_count
    column: scores.Testability.notes
    must_be: '='
    value: 0
    name: scores.Testability.notes_no_missing_values
  - type: missing_count
    column: scores.Maintainability.score
    must_be: '='
    value: 0
    name: scores.Maintainability.score_no_missing_values
  - type: min
    column: scores.Maintainability.score
    must_be: '>='
    value: 3.0
    name: scores.Maintainability.score_min_value
  - type: max
    column: scores.Maintainability.score
    must_be: <=
    value: 5.0
    name: scores.Maintainability.score_max_value
  - type: missing_count
    column: scores.Maintainability.evidence
    must_be: '='
    value: 0
    name: scores.Maintainability.evidence_no_missing_values
  - type: missing_count
    column: scores.Maintainability.notes
    must_be: '='
    value: 0
    name: scores.Maintainability.notes_no_missing_values
lineage:
  downstream: []
